<?php

use Illuminate\Database\Seeder;

class UpdatePermissionsDescriptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        //admin
        $admin = [
        'list_any_institution' => __("permissions.admin.list_any_institution",null,app()->getLocale()),
        'store_any_institution' => 'Ajouter une institution',
        'update_any_institution' => 'Modifier une institution',
        'destroy_any_institution' => 'Supprimer une institution',
        'show_any_institution' => 'Afficher une institution',
        'list_category_client' => 'Voir les categories de client',
        'store_category_client' => 'Ajouter une categorie de client',
        'update_category_client' => 'Modifier une categorie de client',
        'destroy_category_client' => 'Supprimer une categorie de client',
        'show_category_client' => 'Afficher une categorie de client',
        'list_channel' => 'Voir la liste des canaux',
        'store_channel' => 'Ajouter un canal',
        'update_channel' => 'Modifier un canal',
        'destroy_channel' => 'Supprimer un canal',
        'show_channel' => 'Afficher un canal',
        'list_claim_category' => 'Voir les categories de reclamation',
        'store_claim_category' => 'Ajouter une categorie de reclamation',
        'update_claim_category' => 'Modifier une categorie de reclamation',
        'destroy_claim_category' => 'Supprimer une categorie de reclamation',
        'show_claim_category' => 'Afficher une categorie de reclamation',
        'list_claim_object' => 'Voir les objets de reclamation',
        'store_claim_object' => 'Ajouter un objet de reclamation',
        'update_claim_object' => 'Modifier un objet reclamation',
        'destroy_claim_object' => 'Supprimer un objet de reclamation',
        'show_claim_object' => 'Afficher un objet de reclamation',
        'update_claim_object_requirement' => 'Modifier l\'exigence de l\'objet de reclamation',
        'list_client_from_any_institution' => 'Voir les clients des institutions',
        'store_client_from_any_institution' => 'Ajouter un client d\'une institution',
        'update_client_from_any_institution' => 'Modifier un client d\'une institution',
        'destroy_client_from_any_institution' => 'Supprimer un client d\'une institution',
        'show_client_from_any_institution' => 'Afficher un client d\'une institution',
        'show_mail_parameters' => 'Voir les parametres de mail',
        'update_mail_parameters' => 'Modifier les parametres de mail',
        'show_sms_parameters' => 'Afficher un parametre de SMS',
        'update_sms_parameters' => 'Modifier un parametre de SMS',
        'list_currency' => 'Voir les devises ',
        'store_currency' => 'Ajouter une devise',
        'update_currency' => 'Modifier une devise',
        'destroy_currency' => 'Supprimer une devise',
        'show_currency' => 'Afficher une devise',
        'show_dashboard_data_all_institution' => 'Voir les données du tableau de bord de toutes les institutions',
        'list_faq_category' => 'Voir les categories de faq',
        'store_faq_category' => 'Ajouter une categorie de faq',
        'update_faq_category' => 'Modifier une categorie de faq',
        'destroy_faq_category' => 'Supprimer une categorie de faq',
        'show_faq_category' => 'Afficher une categories de faq',
        'list_message_apis' => 'Voir la liste des API de message',
        'store_message_apis' => 'Ajouter un api de message',
        'update_message_apis' => 'Modifier un api de message',
        'destroy_message_apis' => 'Supprimer un api de message',
        'update_institution_message_api' => 'Modifier un api de message d\'une institution',
        'update_my_institution_message_api' => 'Modifier l\'api de message de mon institution',
        'list_position' => 'Voir les positions',
        'store_position' => 'Ajouter une position',
        'update_position' => 'Modifier une position',
        'destroy_position' => 'Supprimer une position',
        'show_position' => 'Afficher une position',
        'list_unit_type' => 'Voir les types d\'unites',
        'store_unit_type' => 'Ajouter un type d\'unite',
        'update_unit_type' => 'Modifier un type d\'unite',
        'destroy_unit_type' => 'Supprimer un type d\'unite',
        'show_unit_type' => 'Afficher un type d\'unite',
        'list_any_unit' => 'Voir les unites',
        'store_any_unit' => 'Ajouter une unite',
        'update_any_unit' => 'Modifier une unite',
        'destroy_any_unit' => 'Supprimer une unite',
        'show_any_unit' => 'Afficher une unite',
        'list_category_client_from_my_institution' => 'Voir les categories de client de mon institution',
        'store_category_client_from_my_institution' => 'Ajouter une categorie de client de mon institution',
        'update_category_client_from_my_institution' => 'Modifier une categorie de client de mon institution',
        'destroy_category_client_from_my_institution' => 'Supprimer une categorie de client de mon institution',
        'show_category_client_from_my_institution' => 'Afficher une categorie de client de mon institution',
        'update_notifications' => 'Modifier les notifications',
        'list_performance_indicator' => 'Voir les indicateurs de performance',
        'store_performance_indicator' => 'Ajouter un indicateur de performance',
        'update_performance_indicator' => 'Modifier un indicateur de performance',
        'destroy_performance_indicator' => 'Supprimer un indicateur de performance',
        'show_performance_indicator' => 'Afficher un indicateur de performance',
        'edit_performance_indicator' => 'Aditer un indicateur de performance',
        'update_processing_circuit_any_institution' => 'Modifier le circuit de traitement de toutes institutions',
        'list_severity_level' => 'Voir les niveaux de gravite',
        'update_severity_level' => 'Modifier un niveau de gravite',
        'show_severity_level' => 'Afficher un niveau de gravite',
        'list_staff_from_any_unit' => 'Voir les staffs de toutes unites',
        'store_staff_from_any_unit' => 'Ajouter un staff d\'une unite',
        'update_staff_from_any_unit' => 'Modifier un staff d\'une unite',
        'destroy_staff_from_any_unit' => 'Supprimer un staff d\'une unite',
        'show_staff_from_any_unit' => 'Afficher un staff d\'une unite',
        'edit_staff_from_any_unit' => 'Editer un staff d\'une unite',
        'list_account_type' => 'Voir les types de compte',
        'show_account_type' => 'Afficher un type de compte',
        'update_account_type' => 'Modifier un type de compte',
        'store_account_type' => 'Ajouter un type de compte',
        'destroy_account_type' => 'Supprimer un type de compte',
        'list_user_any_institution' => 'Voir les utilisateurs de toutes institutions',
        'show_user_any_institution' => 'Afficher un utilisateur d\'une institution',
        'store_user_any_institution' => 'Ajouter un utilisateur d\'une institution',
        'list_delai_qualification_parameters' => 'Voir les parametres du delai de qualification',
        'show_delai_qualification_parameters' => 'Afficher les parametres du delai de qualification',
        'store_delai_qualification_parameters' => 'Ajouter un parametre du delai de qualification',
        'destroy_delai_qualification_parameters' => 'Supprimer un parametre du delai de qualification',
        'list_delai_treatment_parameters' => 'Voir les parametres de delai de traitement',
        'show_delai_treatment_parameters' => 'Afficher un parametre de delai de traitement',
        'store_delai_treatment_parameters' => 'Ajouter un parametre de delai de traitement',
        'destroy_delai_treatment_parameters' => 'Supprimer un parametre de delai de traitement',
        'update_components_parameters' => 'Modifier les parametres des composants',
        'list_any_institution_type_role' => 'Voir les types de rôle de toutes institutions',
        'show_any_institution_type_role' => 'Afficher un type de rôle d\'une institution',
        'store_any_institution_type_role' => 'Ajouter un type de rôle d\'une institution',
        'update_any_institution_type_role' => 'Modifier un type de rôle d\'une institution',
        'destroy_any_institution_type_role' => 'Supprimer un type de rôle d\'une institution',
        'update_active_pilot' => 'Modifier le pilot actif',
        'update_recurrence_alert_settings' => 'Modifier les parametres d\'alerte de récurrence',
        'update_reject_unit_transfer_parameters' => 'Modifier les parametres de transfert d\'unite de rejet',
        'update_min_fusion_percent_parameters' => 'Modifier les parametres de pourcentage minimum de fusion ',
        'update_relance_parameters' => 'Modifier les parametres de relance',
        'update_measure_preventive_parameters' => 'Modifier les parametres des mesures preventives',
        'show_faq' => 'Afficher une faq',
        'store_faq' => 'Ajouter une faq',
        'update_faq' => 'Modifier une faq',
        'delete_faq' => 'Supprimer une faq',
        'search_claim_any_reference' => 'Rechercher une reclamation d\'une reference',
        'list_auth_config' => 'Voir les configurations d\'authentification',
        'update_auth_config' => 'Modifier les configurations d\'authentification ',
        'activity_log' => 'Voir le journal d\'activite ',
        'list_any_notification_proof' => 'Voir toute preuve de notification',
        'list_client_from_my_institution' => 'Voir les clients de mon institution',
        'store_client_from_my_institution' => 'Ajouter un client de mon institution',
        'update_client_from_my_institution' => 'Modifier un client de mon institution',
        'destroy_client_from_my_institution' => 'Supprimer un client de mon institution',
        'show_client_from_my_institution' => 'fficher un client de mon institution',
        'update_my_institution' => '',
        'list_my_unit' => '',
        'store_my_unit' => '',
        'update_my_unit' => '',
        'destroy_my_unit' => '',
        'show_my_unit' => '',
        'update_processing_circuit_my_institution' => '',
        'list_staff_from_my_unit' => '',
        'store_staff_from_my_unit' => '',
        'update_staff_from_my_unit' => '',
        'destroy_staff_from_my_unit' => '',
        'show_staff_from_my_unit' => '',
        'show_dashboard_data_my_institution' => '',
        'list_user_my_institution' => '',
        'show_user_my_institution' => '',
        'store_user_my_institution' => '',
        'list_my_institution_type_role' => '',
        'show_my_institution_type_role' => '',
        'store_my_institution_type_role' => '',
        'update_my_institution_type_role' => '',
        'destroy_my_institution_type_role' => '',
        'search_claim_my_reference' => '',
        'my_email_claim_configuration' => '',
        'list_notification_proof' => '',
        'list_without_link_unit' => '',
        'store_without_link_unit' => '',
        'update_without_link_unit' => '',
        'destroy_without_link_unit' => '',
        'show_without_link_unit' => '',
        'update_processiong_circuit_without_institution' => '',
        'list_relationship' => '',
        'store_relationship' => '',
        'update_relationship' => '',
        'destroy_relationship' => '',
        'show_relationship' => '',
        'list_staff_from_maybe_no_unit' => '',
        'store_staff_from_maybe_no_unit' => '',
        'update_staff_from_maybe_no_unit' => '',
        'destroy_staff_from_maybe_no_unit' => '',
        'show_staff_from_maybe_no_unit' => '',
        "any_email_claim_configuration",
    ];

        //collector
        $collector = [
        'store_claim_against_any_institution' => '',
        'list_satisfaction_measured_my_claim' => '',
        'update_satisfaction_measured_my_claim' => '',
        'show_dashboard_data_my_activity' => '',
        'list_claim_incomplete_against_any_institution' => '',
        'show_claim_incomplete_against_any_institution' => '',
        'update_claim_incomplete_against_any_institution' => '',
        'history_list_create_claim' => '',
        'search_claim_any_reference' => '',
        'attach_files_to_claim' => '',
        'revive_staff' => '',
        'store_claim_without_client' => '',
        'list_satisfaction_measured_any_claim' => '',
        'update_satisfaction_measured_any_claim' => '',
        'list_claim_incomplete_without_client' => '',
        'show_claim_incomplete_without_client' => '',
        'update_claim_incomplete_without_client' => '',
        'store_claim_against_my_institution' => '',
        'list_claim_incomplete_against_my_institution' => '',
        'show_claim_incomplete_against_my_institution' => '',
        'update_claim_incomplete_against_my_institution' => '',
        'search_claim_my_reference' => '',

    ];

        //pilot
        $pilot = [
        'list_claim_awaiting_assignment' => 'Voir les réclamations en attente d\'affectation',
        'show_claim_awaiting_assignment' => 'Afficher une réclamation en attente d\'affectation',
        'merge_claim_awaiting_assignment' => 'Fusionner une réclamation en attente d\'affectation',
        'store_claim_against_any_institution' => 'Ajouter une reclamation d\'une institution',
        'list_claim_awaiting_validation_my_institution' => 'Voir les reclamations en attente de validation de mon institution',
        'show_claim_awaiting_validation_my_institution' => 'Afficher les reclamations en attente de validation de mon institution',
        'validate_treatment_my_institution' => 'Valider un traitement de mon institution',
        'list_satisfaction_measured_my_claim' => 'Voir les mesures de satisfaction d\'une reclamation',
        'update_satisfaction_measured_my_claim' => 'Modifier une mesure de satisfaction d\'une reclamation',
        'show_dashboard_data_all_institution' => 'Afficher les donnees du tableau de bord de toutes institutions',
        'show_dashboard_data_my_institution' => 'Afficher les donnees du tableau de bord de mon institution',
        'list_my_discussions' => 'Voir mes discussions',
        'list_discussion_contributors' => 'Voir les contibuteurs de la discussion',
        'contribute_discussion' => 'Contribuer une discussion',
        'list_monitoring_claim_any_institution' => 'Voir la supervision des reclamations de toutes institutions',
        'list_reporting_claim_any_institution' => 'Voir le rapport des reclamations de toutes institutions',
        'transfer_claim_to_circuit_unit' => 'Tranferer une reclamation a une unite',
        'transfer_claim_to_targeted_institution' => 'transferer une reclamation ',
        'list_claim_incomplete_against_any_institution' => 'Voir les reclamations incompletes de toutes institutions',
        'show_claim_incomplete_against_any_institution' => 'Afficher une reclamation incomplete de toutes institutions',
        'update_claim_incomplete_against_any_institution' => 'Modifier une reclamation incomplete de toutes institutions',
        'list_any_claim_archived' => 'Voir les reclamations archivees',
        'show_any_claim_archived' => 'Afficher une reclamation archivee',
        'history_list_create_claim' => 'Historique des reclamations créees',
        'update_active_pilot' => 'Modifier le pilot actif',
        'unfounded_claim_awaiting_assignment' => 'Voir les reclamations non fondees en attente d\'affectation ',
        'search_claim_any_reference' => 'Rechercher une reclamation de toute reference',
        'attach_files_to_claim' => 'Joindre un fichier a une reclamation',
        'revive_staff' => 'Relancer un personnel',
        'pilot_list_any_notification_proof' => 'Les preuves de notification du pilot',
        'store_claim_against_my_institution' => '',
        'list_my_claim_archived' => '',
        'show_my_claim_archived' => '',
        'list_monitoring_claim_my_institution' => '',
        'list_reporting_claim_my_institution' => '',
        'list_claim_incomplete_against_my_institution' => '',
        'show_claim_incomplete_against_my_institution' => '',
        'update_claim_incomplete_against_my_institution' => '',
        'search_claim_my_reference' => '',
        'pilot_list_notification_proof' => '',
        'store_claim_without_client' => '',
        'list_claim_awaiting_validation_any_institution' => '',
        'show_claim_awaiting_validation_any_institution' => '',
        'validate_treatment_any_institution' => '',
        'list_satisfaction_measured_any_claim' => '',
        'update_satisfaction_measured_any_claim' => '',
        'transfer_claim_to_unit' => '',
        'list_claim_incomplete_without_client' => '',
        'show_claim_incomplete_without_client' => '',
        'update_claim_incomplete_without_client' => '',
    ];

        //staff
        $staff = [
        'list_claim_awaiting_treatment' => '',
        'show_claim_awaiting_treatment' => '',
        'rejected_claim_awaiting_treatment' => '',
        'self_assignment_claim_awaiting_treatment' => '',
        'assignment_claim_awaiting_treatment' => '',
        'list_claim_assignment_to_staff' => '',
        'show_claim_assignment_to_staff' => '',
        'list_my_discussions' => '',
        'store_discussion' => '',
        'destroy_discussion' => '',
        'list_discussion_contributors' => '',
        'add_discussion_contributor' => '',
        'remove_discussion_contributor' => '',
        'contribute_discussion' => '',
        'show_dashboard_data_my_unit' => '',
        'show_dashboard_data_my_activity' => '',
        'history_list_treat_claim' => '',
        'search_claim_any_reference' => '',
        'attach_files_to_claim' => '',
        'search_claim_my_reference' => '',
    ];

    }
}
